### ISSUE TITLE
object-merge-advanced: add support for Date objects

### ISSUE THREAD

**Issue by revelt** [codsen/codsen#1]
> Does mergeAdvanced merge Date objects? We couldn’t make it work.
> const o1 = { ttl: ‘2020-02-08T12:32:00’} const o2 = { ttl: ‘2020-02-10T02:32:00’} const res = mergeAdvanced(o1, o2) console.log(res)
> The result is res = { ttl: ‘2020-02-08T12:32:00’}, but we are expecting { ttl: ‘2020-02-10T02:32:00’

as reported by ~wefa2011 in our old issue tracker on Sourcehut

**Comment by wefa2020** [comment]
@revelt any update?

**Comment by revelt** [comment]
hi! Sorry for delay, it's in progress. So far, I've implemented: finite date vs. finite date, also merging when either one is not finite (`{ ttl: new Date("") }`). There are few more variations to cover, date vs boolean and so on. I want to make it properly, we also need to update the [merging chart](https://codsen.com/images/package-object-merge-advanced-algorithm.png). 

How badly do you need it before weekend? There are few other features pending releasing and I'd be keen to get all this published over the weekend, as usual.

**Comment by wefa2020** [comment]
Thanks revelt! We will release our product in about 2 weeks. So, we still have time. Please keep us posted once a PR is available.

**Comment by revelt** [comment]
v.12.0.0 has been released, please check

**Comment by wefa2020** [comment]
Hi Roy,

I am not sure why issue #1 is closed. I installed the 12.0.1 version. Date are still not  merged. Am I missing anything?

Thanks!

Wei

**Comment by revelt** [comment]
hi Wei,
Please help to assemble the test for TDD, try console-logging the problem at: https://npm.runkit.com/object-merge-advanced — you can share the link, each test is public once you save — try recreating the issue — I need something to put into tests.
thank you

**Comment by revelt** [comment]
I'm asking because in the examples you provided, values are string vs string: `const o1 = { ttl: ‘2020-02-08T12:32:00’}` — the `‘2020-02-08T12:32:00’` seems to be a string. I did implement two _date object merging_ but not _date string merging_. In theory, we could use regexes and evaluate every string but that can be done using [callback](https://codsen.com/os/object-merge-advanced/#optscb), `opts.cb`. My reasoning is that every feature slows down the app and the main purpose of this program is merging JSON data, in context of email/web templating.

If I overlooked something in `Date` objects, I'll fix. If the merging is for text strings, I'd rather suggest to use `opts.cb`, see the [examples](https://codsen.com/os/object-merge-advanced/#optscb-bigger-example-number-two).

**Comment by wefa2020** [comment]
Hi Roy,

I will write a test so you can see I am merging  2 date objects. They look
like strings because I copied the data from my debugger watch window. I do
agree with you that we need to pay attention to the app performance.
Currently, I am using a cb to merge Boolean and dates. The cb works for us.
Maybe we should consider rolling back version 12 (date and Boolean
changes). We do have perf concerns of the version. A quick question. Will
cb slow the app down? below is our code

export const mergeParam =  {
    cb: (inputArg1: any, inputArg2: any, resultAboutToBeReturned: any,
infoObj: any) => {
      if (typeof inputArg1 === 'boolean' && typeof inputArg2 === 'boolean'
) {
        return inputArg2
      }
      if (inputArg1 instanceof Date && inputArg2 instanceof Date) {
        return inputArg2
      }
      return resultAboutToBeReturned
    }
  }

Thanks!

Wei

Sent from my iPhone

On Feb 14, 2021, at 11:05 AM, Roy Revelt <notifications@github.com> wrote:

﻿

I'm asking because in the examples you provided, values are string vs
string: const o1 = { ttl: ‘2020-02-08T12:32:00’} — the ‘2020-02-08T12:32:00’
seems to be a string. I did implement two *date object merging* but not *date
string merging*. In theory, we could use regexes and evaluate every string
but that can be done using callback
<https://codsen.com/os/object-merge-advanced/#optscb>, opts.cb. My
reasoning is that every feature slows down the app and the main purpose of
this program is merging JSON data, in context of email/web templating.

If I overlooked something in Date objects, I'll fix. If the merging is for
text strings, I'd rather suggest to use opts.cb, see the examples
<https://codsen.com/os/object-merge-advanced/#optscb-bigger-example-number-two>
.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/codsen/codsen/issues/1#issuecomment-778825208>, or
unsubscribe

**Comment by revelt** [comment]
hi Wei! Happy Friday!
Sorry for late response. It's been a bit hectic lately.

> Will cb slow the app down?
Yes, instead of returning a value, a function is called. However, perf difference is questionable, it depends on the context. JS is slow anyway, for speed-critical operations I'd use Go or even Rust. I created `object-merge-advanced` to merge CRM templating data, it works brilliantly, we merge JSON mainly.

Regarding the _perf_, I keep all [historical records](https://github.com/codsen/codsen/blob/main/packages/object-merge-advanced/perf/historical.json) of each version, numbers are not CPU-normalised (idea for another side project 🥇 ), it depends did I ran it locally or was it on CI, plus, sometimes I suspect thermal throttling comes in play too. On my local, the `v12.0.5` runs around 11K ops/s., so there are no significant speed differences since I started keeping the records. Smaller number you see in the JSON are from my old laptop, 2013 MBP.

Thank you for considering the `object-merge-advanced` 👍

**Comment by wefa2020** [comment]
Hi Roy,

Sorry for the late reply. I was really busy in the past week. we actually
rolled back to version 11.0.2. The reason is that boolean and date merge
don't work for us. So,  we decide to use  mergeAdvanced(doc as Sde, sde, {
hardMergeEverything: true}). It gives us the desired behavior. The
performance of the library is good. we just see a lot of date manipulation
code in version 12 that doesn't help us. So, we opted to use the previous
version. One weird thing happens to us is that, our cb is not fired on
every property of the objects to be merged. we are not sure why.

Thanks Roy for following up. We love your library!

Wei

**Comment by revelt** [comment]
hi Wei! Thank you for kind words, in this lockdown it means a lot to me. Should we close this issue? I mean if you guys are all right, then we're set?

**Comment by wefa2020** [comment]
Sure , please close. Thanks Roy! Have a nice weekend!

Wei
